#!/usr/bin/env python3
"""
silver_1k_analysis.py

Describes the 1k silver pilot (data/silver/pilot_1k.jsonl) and compares its surface
variety against exact matching **on the same 1,000 abstracts**.

The comparison scope matters: the headline "105 case-folded surface forms" in
playground/exact_match_analysis.md is measured over the whole corpus (10,329
articles, abstract + full_text). This script re-measures exact matching restricted
to the pilot's 1,000 pmids and abstract-only spans, so both sides are counted on
identical text.

This is a **descriptive** analysis. It cannot say how *correct* the silver labels
are — there is no ground truth on these 1,000 abstracts. Precision only comes from
the doccano human review.

Output: playground/silver_1k_analyses.md

Run from repo root:
    venv310/bin/python3 playground/silver_1k_analysis.py
"""

import json
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SILVER = ROOT / "data/silver/pilot_1k.jsonl"
MATCHES = ROOT / "data/processed/exact_matches.jsonl"
OUT = ROOT / "playground/silver_1k_analyses.md"

# Surfaces containing these read as disease/phenotype names, not pathways — a
# heuristic false-positive signal we can compute without human review.
DISEASE_RE = re.compile(r"\b(disease|disorder|deficiency|syndrome|aemia|emia)\b|"
                        r"(disorders|diseases)\b", re.IGNORECASE)


def fold(s: str) -> str:
    return re.sub(r"\s+", " ", s.lower().strip())


def main() -> None:
    recs = [json.loads(l) for l in SILVER.read_text(encoding="utf-8").splitlines() if l.strip()]
    pmids = {r["pmid"] for r in recs}
    spans = [s for r in recs for s in r["spans"]]

    # ---- exact matching on the SAME pmids, abstract-only ----------------------
    ex_spans, ex_by_pmid = [], defaultdict(list)
    with MATCHES.open(encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            r = json.loads(line)
            if str(r["pmid"]) not in pmids:
                continue
            for sp in r["spans"]:
                if sp.get("source") == "abstract":
                    ex_spans.append((sp["text"], r["pathway_id"]))
                    ex_by_pmid[str(r["pmid"])].append(sp["text"])

    ex_surfaces = {fold(t) for t, _ in ex_spans}
    ex_pathways = {p for _, p in ex_spans}
    ex_pmids_hit = len(ex_by_pmid)

    # ---- silver --------------------------------------------------------------
    sv_surfaces = Counter(fold(s["text"]) for s in spans)
    sv_pathways = {s["canonical"] for s in spans if s["canonical"]}
    mt = Counter(s["match_type"] for s in spans)
    src = Counter(s["source"] for s in spans)
    unmapped = [s for s in spans if s["canonical"] is None]

    spans_per = Counter(len(r["spans"]) for r in recs)
    empty = spans_per[0]

    new_surfaces = set(sv_surfaces) - ex_surfaces
    kept_surfaces = set(sv_surfaces) & ex_surfaces
    missed_surfaces = ex_surfaces - set(sv_surfaces)

    # surfaces per canonical (variation richness)
    per_canon = defaultdict(set)
    for s in spans:
        if s["canonical"]:
            per_canon[s["canonical"]].add(fold(s["text"]))
    rich = sorted(per_canon.items(), key=lambda kv: -len(kv[1]))[:12]

    disease_like = Counter(fold(s["text"]) for s in spans if DISEASE_RE.search(s["text"]))
    long_surfaces = sorted({fold(s["text"]) for s in spans if len(s["text"]) > 60})

    booster_only = {fold(s["text"]) for s in spans if s["source"] == "booster"}
    llm_only = {fold(s["text"]) for s in spans if s["source"] == "llm_silver"}

    L = []
    A = L.append
    A("# Silver 1k pilot — descriptive analysis\n")
    A("Source: `data/silver/pilot_1k.jsonl` (generated by `llm/run_silver.py`, "
      "`qwen2.5:14b`, no-vocab + lenient + synonyms, plus `llm/booster.py`).\n")
    A("> **This is descriptive, not an evaluation.** There is no ground truth on these\n"
      "> 1,000 abstracts, so nothing here says how *correct* the labels are. Precision\n"
      "> comes only from the doccano human review (`data/silver/ANNOTATION_GUIDE.md`).\n"
      "> Related: `playground/exact_match_analysis.md`, `playground/golden_set/README.md`.\n")

    A("## Scope\n")
    A("| | |")
    A("|---|---|")
    A(f"| Abstracts (pmids) | {len(pmids):,} |")
    A(f"| — with ≥1 silver span | {len(pmids) - empty:,} ({100*(len(pmids)-empty)/len(pmids):.0f}%) |")
    A(f"| — with 0 spans | {empty:,} ({100*empty/len(pmids):.0f}%) |")
    A(f"| Total spans | {len(spans):,} ({len(spans)/len(pmids):.1f} per abstract) |")
    A(f"| **Unique surface forms** (case-folded) | **{len(sv_surfaces):,}** |")
    A("\nText scope is **abstract-only**, matching the golden set.\n")

    A("## Headline — did we break the near-lookup problem?\n")
    A("The whole motivation: exact matching produced only 105 case-folded surface forms "
      "across 73k spans corpus-wide, so a model trained on it learns a lookup table. "
      "Both sides below are counted on the **same 1,000 abstracts, abstract-only**.\n")
    A("| | Exact matching | Silver (LLM + booster) |")
    A("|---|---|---|")
    A(f"| Spans | {len(ex_spans):,} | {len(spans):,} |")
    A(f"| **Unique surface forms** | **{len(ex_surfaces):,}** | **{len(sv_surfaces):,}** "
      f"({len(sv_surfaces)/max(1,len(ex_surfaces)):.1f}×) |")
    A(f"| Abstracts with ≥1 span | {ex_pmids_hit:,} | {len(pmids)-empty:,} |")
    A(f"| Distinct Recon pathways named | {len(ex_pathways):,} | {len(sv_pathways):,} |")
    A("")
    A(f"- **{len(new_surfaces):,} surface forms are new** — never produced by exact matching "
      f"on these abstracts ({100*len(new_surfaces)/len(sv_surfaces):.0f}% of the silver vocabulary).")
    A(f"- {len(kept_surfaces):,} surfaces overlap with exact matching.")
    A(f"- {len(missed_surfaces):,} exact-matching surfaces are **absent** from silver "
      "(recall gaps — the LLM did not return them).\n")

    A("## Vocabulary coverage (NOT a quality metric)\n")
    A("How many surfaces we could put a Recon name to. **`unmapped` does not mean "
      "'not a pathway'** — it means we could not name it. `kynurenine pathway` is a real "
      "pathway with no Recon subsystem; it is unmapped and still a valid positive for a "
      "binary tagger (labels are `O`/`B-Pathway`/`I-Pathway`; the canonical never enters "
      "the label).\n")
    A("| match_type | spans | share |")
    A("|---|---|---|")
    for k in ("exact", "synonym", "variation", "unmapped"):
        A(f"| `{k}` | {mt[k]:,} | {100*mt[k]/len(spans):.0f}% |")
    A("")
    A(f"- **Mapped to a Recon name: {len(spans)-mt['unmapped']:,} ({100*(len(spans)-mt['unmapped'])/len(spans):.0f}%)** · "
      f"unmapped: {mt['unmapped']:,} ({100*mt['unmapped']/len(spans):.0f}%)")
    A(f"- **The payoff: `variation` + `synonym` = {mt['variation']+mt['synonym']:,} spans "
      f"({100*(mt['variation']+mt['synonym'])/len(spans):.0f}%)** — mentions exact matching "
      "would miss entirely, *plus* an unknown share of the unmapped bucket.")
    A(f"- Unique unmapped surfaces: {len({fold(s['text']) for s in unmapped}):,}\n")

    A("### Most frequent unmapped surfaces\n")
    A("Most are real pathway mentions Recon simply has no name for (`kynurenine pathway`) "
      "or umbrella terms (`lipid metabolism`); a minority are canonicalizer gaps "
      "(`tricarboxylic acid (tca) cycle`, `citrate cycle` — both are the citric acid cycle) "
      "and a small tail is genuine noise for the human to reject (`reductive stress`).\n")
    A("| surface | spans |")
    A("|---|---|")
    un = Counter(fold(s["text"]) for s in unmapped)
    for t, c in un.most_common(15):
        A(f"| `{t}` | {c} |")
    A("")

    A("## Provenance\n")
    A("| source | spans | unique surfaces |")
    A("|---|---|---|")
    A(f"| LLM (`llm_silver`) | {src['llm_silver']:,} | {len(llm_only):,} |")
    A(f"| Booster (`booster`) | {src['booster']:,} | {len(booster_only):,} |")
    A("")
    A(f"- Booster contributes {100*src['booster']/len(spans):.0f}% of spans; "
      f"{len(booster_only - llm_only):,} of its surfaces appear from the booster only.")

    A("## Variation richness — surface forms per pathway\n")
    A("How many distinct ways one pathway gets written. This is the near-lookup problem "
      "measured per pathway: exact matching gives ~1 form per pathway by construction.\n")
    A("| canonical | unique surfaces | examples |")
    A("|---|---|---|")
    for canon, forms in rich:
        ex = ", ".join(f"`{f}`" for f in sorted(forms)[:3])
        A(f"| {canon} | {len(forms)} | {ex} |")
    A("")

    A("## Quality signals we can compute without human review\n")
    A(f"**Disease/phenotype-looking surfaces: {sum(disease_like.values()):,} spans, "
      f"{len(disease_like):,} unique.** These read as disease names, not pathways — the "
      "expected false-positive class for the human to reject.\n")
    if disease_like:
        A("| surface | spans |")
        A("|---|---|")
        for t, c in disease_like.most_common(10):
            A(f"| `{t}` | {c} |")
        A("")
    A(f"**Unusually long surfaces (>60 chars): {len(long_surfaces):,}** — long spans are "
      "often boundary errors or non-pathway phrases.\n")
    for t in long_surfaces[:5]:
        A(f"- `{t}`")
    A("")

    A("## What this does not tell us\n")
    A("- **Precision** — needs the doccano review. Golden measured 0.95 on 5 abstracts; "
      "whether that holds here is unknown.")
    A("- **Recall** — we cannot count mentions the LLM never proposed. Golden put "
      "`span:variation` recall at 5/6 (83%); the `missed_surfaces` count above is a partial "
      "proxy on exact-matchable forms only.")
    A("- **Whether unmapped spans are real pathways** — by construction we could not name "
      "them; only a human can say.\n")

    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"Written: {OUT}")
    print(f"  pmids={len(pmids)} spans={len(spans)} unique_surfaces={len(sv_surfaces)}")
    print(f"  exact-matching same scope: spans={len(ex_spans)} unique_surfaces={len(ex_surfaces)}")
    print(f"  new surfaces={len(new_surfaces)}  unmapped={mt['unmapped']}")


if __name__ == "__main__":
    main()
